# Resolve react_native_pods.rb with node to allow for hoisting
# require Pod::Executable.execute_command('node', ['-p',
#   'require.resolve(
#     "react-native/scripts/react_native_pods.rb",
#     {paths: [process.argv[1]]},
#   )', __dir__]).strip

# $RNFirebaseDisableSPM = true

# platform :ios, min_ios_version_supported
# prepare_react_native_project!


# linkage = ENV['USE_FRAMEWORKS']
# if linkage != nil
#   Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
#   use_frameworks! :linkage => linkage.to_sym
# end

# target 'syilReact' do
#   config = use_native_modules!

#   use_react_native!(
#     :path => config[:reactNativePath],
#     # An absolute path to your application root.
#     :app_path => "#{Pod::Config.instance.installation_root}/.."
#   )


#   post_install do |installer|
#     react_native_post_install(
#       installer,
#       config[:reactNativePath],
#       :mac_catalyst_enabled => false,
#       # :ccache_enabled => true
#     )

#     installer.pods_project.targets.each do |target|
#     if target.name == 'fmt'
#       target.build_configurations.each do |config|
#         config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
#         config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
#         config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'FMT_USE_CONSTEXPR=0'
#       end
#     end
#   end
    
#   end
# end



# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# Force React Native Firebase to use CocoaPods instead of SPM
$RNFirebaseDisableSPM = true

# RNFirebase pods should be static frameworks
$RNFirebaseAsStaticFramework = true

platform :ios, min_ios_version_supported
prepare_react_native_project!

use_frameworks! :linkage => :static

target 'syilReact' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|

        # Allow React headers inside framework pods
        config.build_settings[
          'CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'
        ] = 'YES'

        # Keep inherited flags
        other_cflags =
          config.build_settings['OTHER_CFLAGS'] || ['$(inherited)']

        other_cflags =
          [other_cflags] unless other_cflags.is_a?(Array)

        unless other_cflags.include?(
          '-Wno-non-modular-include-in-framework-module'
        )
          other_cflags <<
            '-Wno-non-modular-include-in-framework-module'
        end

        config.build_settings['OTHER_CFLAGS'] = other_cflags
      end

      if target.name == 'fmt'
        target.build_configurations.each do |config|
          config.build_settings[
            'CLANG_CXX_LANGUAGE_STANDARD'
          ] = 'c++17'

          config.build_settings[
            'GCC_PREPROCESSOR_DEFINITIONS'
          ] ||= ['$(inherited)']

          unless config.build_settings[
            'GCC_PREPROCESSOR_DEFINITIONS'
          ].include?('FMT_USE_CONSTEXPR=0')
            config.build_settings[
              'GCC_PREPROCESSOR_DEFINITIONS'
            ] << 'FMT_USE_CONSTEXPR=0'
          end
        end
      end
    end
  end
end